# If set to true should be run using mpirun
mpi = true

# Could be degree, betweenness, closeness
order_method = "degree"

# Could be metis, patoh, kahypar
partition_engine = "patoh"


# Settings for patoh partitioner (ignored if partition_engine != patoh)
[patoh]
# Could be default, speed, quality
mode = "default"
# Could be cut or con
minimize = "cut"

# Settings for kahypar partitioner (ignored if partition_engine != patoh)
[kahypar]
# Path to the .ini file for kahypar
config_file = "kahypar_config/cut_rKaHyPar_sea20.ini"
